NS = ejsfreitas
VERSION = armv7-1.0.0
REPO = https-portal

.PHONY: build push shell run start stop rm release

build:
	docker build -t $(NS)/$(REPO):$(VERSION) .
push:
	docker push $(NS)/$(REPO):$(VERSION)

default: build
